
APP_NAME = "CoffeeShopPH"
APP_VERSION = "v1.0.0"
APP_DATE = "2015"

PAGE_HOME_NAME = "Home"
PAGE_ABOUT_NAME = "About"
PAGE_HELP_NAME = "FAQ"
PAGE_CONTACT_NAME = "Contact Us"

SIGNUP_PAGE_TITLE = "Sign Up"
SIGNUP_PAGE_HEADER = "Sign Up"

LOGIN_PAGE_TITLE = "Login"
LOGIN_PAGE_HEADER = "Login"

USERS_PAGE_TITLE = "Users"
USERS_PAGE_HEADER = "Users"
USERS_DEFAULT_PER_PAGE = 20
USERS_DEFAULT_ORDER_BY = "name ASC"

PASSWORD_RESET_PAGE_TITLE = "Reset"
PASSWORD_RESET_PAGE_HEADER = "Password Reset"

ORDERS_PAGE_TITLE = "Orders"
ORDERS_PAGE_HEADER = "Orders"
